CREATE TABLE Players
(Player_id
 INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(100) NOT NULL,
 Position VARCHAR(100) NOT NULL,
 Team_id MEDIUMINT NOT NULL,
 CONSTRAINT fk_team_id
 FOREIGN KEY (Team_id) REFERENCES Teams (Team_id)
 ON DELETE CASCADE
 ON UPDATE RESTRICT);
