CREATE TABLE Stats
(Game_id INT NOT NULL,
 Player_id INT NOT NULL,
 Set_ TINYINT(2) NOT NULL,
 Attack_n TINYINT(2) ZEROFILL,
 Attack_k TINYINT(2) ZEROFILL,
 Attack_e TINYINT(2) ZEROFILL,
 Block_t TINYINT(2) ZEROFILL,
 Block_k TINYINT(2) ZEROFILL,
 ServeR_er TINYINT(2) ZEROFILL,
 ServeR_p TINYINT(2) ZEROFILL,
 ServeR_g TINYINT(2) ZEROFILL,
 ServeR_ex TINYINT(2) ZEROFILL,
 Serve_e TINYINT(2) ZEROFILL,
 Serve_a TINYINT(2) ZEROFILL,
 Serve_n TINYINT(2) ZEROFILL,
 PRIMARY KEY (Game_id,Player_id,Set_),
 CONSTRAINT fk_game_id FOREIGN KEY (Game_id) REFERENCES Games (Game_id)
 ON DELETE CASCADE
 ON UPDATE RESTRICT,
 CONSTRAINT fk_player_id FOREIGN KEY (Player_id) REFERENCES Players (Player_id)
 ON DELETE CASCADE
 ON UPDATE RESTRICT);
