CREATE TABLE Games
(Game_id
 INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 Opp_id MEDIUMINT NOT NULL,
 Team_id MEDIUMINT NOT NULL,
 Date DATE NOT NULL,
 CONSTRAINT fk_opp_id FOREIGN KEY (Opp_id) REFERENCES Teams (Team_id)
 ON DELETE CASCADE
 ON UPDATE RESTRICT,
 CONSTRAINT fk_t_id FOREIGN KEY (Team_id) REFERENCES Teams (Team_id)
 ON DELETE CASCADE
 ON UPDATE RESTRICT);
